Repository UMC-Umark/umark-server, pull requests merged in 2024-02, with the labels that each got.

#33 Feature/27-회원 탈퇴
  src/main/java/umc/project/umark/domain/member/controller/MemberController.java
  src/main/java/umc/project/umark/domain/member/entity/Member.java
  src/main/java/umc/project/umark/domain/member/service/MemberService.java
  src/main/java/umc/project/umark/domain/member/service/MemberServiceImpl.java
Labels: feature

#35 Feature/34-약관 추가 및 전체 조회
  src/main/java/umc/project/umark/domain/term/controller/TermController.java
  src/main/java/umc/project/umark/domain/term/converter/TermConverter.java
  src/main/java/umc/project/umark/domain/term/dto/TermDto.java
  src/main/java/umc/project/umark/domain/term/entity/Term.java
  src/main/java/umc/project/umark/domain/term/service/TermService.java
  src/main/java/umc/project/umark/domain/term/service/TermServiceImpl.java
Labels: feature

#32 북마크에 대한 신고 기능
  src/main/java/umc/project/umark/UmarkApplication.java
  src/main/java/umc/project/umark/domain/bookmark/controller/BookMarkController.java
  src/main/java/umc/project/umark/domain/bookmark/converter/BookMarkConverter.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Request/BookMarkRequest.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkService.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkServiceImpl.java
  src/main/java/umc/project/umark/domain/report/Report.java
  src/main/java/umc/project/umark/domain/report/ReportType.java
  src/main/java/umc/project/umark/domain/report/converter/ReportConverter.java
  src/main/java/umc/project/umark/domain/report/dto/Request/ReportRequest.java
  src/main/java/umc/project/umark/domain/report/dto/Response/ReportResponse.java
  src/main/java/umc/project/umark/domain/report/repository/ReportRepository.java
Labels: feature

#39 [FEAT] #38-이벤트 조회 수정 api
  src/main/java/umc/project/umark/UmarkApplication.java
  src/main/java/umc/project/umark/domain/bookmark/controller/BookMarkController.java
  src/main/java/umc/project/umark/domain/bookmark/converter/BookMarkConverter.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Request/BookMarkRequest.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Response/BookMarkInquiryResponse.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Response/BookMarkUpdateResponse.java
  src/main/java/umc/project/umark/domain/bookmark/entity/BookMark.java
  src/main/java/umc/project/umark/domain/bookmark/repository/BookMarkRepository.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkService.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkServiceImpl.java
  src/main/java/umc/project/umark/domain/mapping/repository/BookMarkLikeRepository.java
  src/main/java/umc/project/umark/global/common/BaseEntity.java
  src/main/java/umc/project/umark/global/exception/GlobalErrorCode.java
Labels: feature

#42 1차 테스팅 서버 배포
  .gitignore
  build.gradle
  src/main/java/umc/project/umark/UmarkApplication.java
  src/main/java/umc/project/umark/domain/bookmark/controller/BookMarkController.java
  src/main/java/umc/project/umark/domain/bookmark/converter/BookMarkConverter.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Request/BookMarkRequest.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Response/BookMarkInquiryResponse.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Response/BookMarkResponse.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Response/BookMarkUpdateResponse.java
  src/main/java/umc/project/umark/domain/bookmark/entity/BookMark.java
  src/main/java/umc/project/umark/domain/bookmark/repository/BookMarkRepository.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkService.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkServiceImpl.java
  src/main/java/umc/project/umark/domain/hashtag/converter/HashTagConverter.java
  src/main/java/umc/project/umark/domain/hashtag/entity/HashTag.java
  src/main/java/umc/project/umark/domain/hashtag/repository/HashTagRepository.java
  src/main/java/umc/project/umark/domain/hashtag/service/HashTagService.java
  src/main/java/umc/project/umark/domain/hashtag/service/HashTagServiceImpl.java
  src/main/java/umc/project/umark/domain/mapping/BookMarkHashTag.java
  src/main/java/umc/project/umark/domain/mapping/BookMarkLike.java
  src/main/java/umc/project/umark/domain/mapping/converter/BookMarkHashTagConverter.java
  src/main/java/umc/project/umark/domain/mapping/converter/BookMarkLikeConverter.java
  src/main/java/umc/project/umark/domain/mapping/dto/BookMarkLikeResponse.java
  src/main/java/umc/project/umark/domain/mapping/repository/BookMarkLikeRepository.java
  src/main/java/umc/project/umark/domain/member/controller/MemberController.java
  src/main/java/umc/project/umark/domain/member/converter/MemberConverter.java
  src/main/java/umc/project/umark/domain/member/dto/MemberDto.java
  src/main/java/umc/project/umark/domain/member/entity/Member.java
  src/main/java/umc/project/umark/domain/member/entity/MemberStatus.java
  src/main/java/umc/project/umark/domain/member/repository/MemberRepository.java
  src/main/java/umc/project/umark/domain/member/service/MemberService.java
  src/main/java/umc/project/umark/domain/member/service/MemberServiceImpl.java
  src/main/java/umc/project/umark/domain/report/Report.java
  src/main/java/umc/project/umark/domain/report/ReportType.java
  src/main/java/umc/project/umark/domain/report/converter/ReportConverter.java
  src/main/java/umc/project/umark/domain/report/dto/Request/ReportRequest.java
  src/main/java/umc/project/umark/domain/report/dto/Response/ReportResponse.java
  src/main/java/umc/project/umark/domain/report/repository/ReportRepository.java
  src/main/java/umc/project/umark/domain/term/controller/TermController.java
  src/main/java/umc/project/umark/domain/term/converter/TermConverter.java
  src/main/java/umc/project/umark/domain/term/dto/TermDto.java
  src/main/java/umc/project/umark/domain/term/entity/Term.java
  src/main/java/umc/project/umark/domain/term/repository/TermRepository.java
  src/main/java/umc/project/umark/domain/term/service/TermService.java
  src/main/java/umc/project/umark/domain/term/service/TermServiceImpl.java
  src/main/java/umc/project/umark/global/common/ApiResponse.java
  src/main/java/umc/project/umark/global/common/BaseEntity.java
  src/main/java/umc/project/umark/global/exception/ApiResponse.java
  src/main/java/umc/project/umark/global/exception/GlobalErrorCode.java
  src/main/java/umc/project/umark/global/exception/GlobalException.java
  src/main/java/umc/project/umark/global/exception/GlobalExceptionHandler.java
Labels: feature

#45 Feature/#31 create report
  src/main/java/umc/project/umark/domain/bookmark/controller/BookMarkController.java
  src/main/java/umc/project/umark/domain/bookmark/entity/BookMark.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkService.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkServiceImpl.java
  src/main/java/umc/project/umark/domain/report/converter/ReportConverter.java
  src/main/java/umc/project/umark/domain/report/dto/Response/ReportResponse.java
Labels: refactor

#48 [FIX]: 회원가입 시, 동의한 약관번호 반환
  src/main/java/umc/project/umark/domain/member/controller/MemberController.java
  src/main/java/umc/project/umark/domain/member/converter/MemberConverter.java
  src/main/java/umc/project/umark/domain/member/dto/MemberDto.java
  src/main/java/umc/project/umark/domain/member/entity/Member.java
  src/main/java/umc/project/umark/domain/member/service/MemberServiceImpl.java
  src/main/java/umc/project/umark/domain/term/entity/Term.java
Labels: feature

#56 Feature/52-로그인 기능 구현
  src/main/java/umc/project/umark/domain/bookmark/entity/BookMark.java
  src/main/java/umc/project/umark/domain/member/auth/UserDetailsServiceImpl.java
  src/main/java/umc/project/umark/domain/member/auth/utils/MemberUtils.java
  src/main/java/umc/project/umark/domain/member/auth/utils/SecurityUtils.java
  src/main/java/umc/project/umark/domain/member/controller/MemberController.java
  src/main/java/umc/project/umark/domain/member/converter/MemberConverter.java
  src/main/java/umc/project/umark/domain/member/dto/MemberDto.java
  src/main/java/umc/project/umark/domain/member/entity/Member.java
  src/main/java/umc/project/umark/domain/member/entity/MemberRole.java
  src/main/java/umc/project/umark/domain/member/service/MemberService.java
  src/main/java/umc/project/umark/domain/member/service/MemberServiceImpl.java
  src/main/java/umc/project/umark/global/config/ConfigurationPropertiesConfig.java
  src/main/java/umc/project/umark/global/config/SecurityConfig.java
  src/main/java/umc/project/umark/global/consts/UmarkStatic.java
  src/main/java/umc/project/umark/global/exception/ApiResponse.java
  src/main/java/umc/project/umark/global/exception/GlobalErrorCode.java
  src/main/java/umc/project/umark/global/jwt/JwtFilter.java
  src/main/java/umc/project/umark/global/jwt/JwtProperties.java
  src/main/java/umc/project/umark/global/jwt/JwtTokenService.java
  src/main/java/umc/project/umark/global/jwt/dto/AccessTokenInfo.java
  src/main/java/umc/project/umark/global/security/CorsConfig.java
  src/main/java/umc/project/umark/global/security/JwtFilter.java
  src/main/java/umc/project/umark/global/security/JwtSecurityConfig.java
  src/main/java/umc/project/umark/global/security/RefreshToken.java
  src/main/java/umc/project/umark/global/security/RefreshTokenRepository.java
  src/main/java/umc/project/umark/global/security/SecurityConfiguration.java
  src/main/java/umc/project/umark/global/security/TokenDto.java
  src/main/java/umc/project/umark/global/security/TokenProvider.java
  src/main/java/umc/project/umark/global/security/TokenRequestDto.java
Labels: feature

#60 [FEAT]: 인증 동작 추가 및 스웨거 추가
  build.gradle
  src/main/java/umc/project/umark/domain/bookmark/controller/BookMarkController.java
  src/main/java/umc/project/umark/domain/bookmark/dto/Request/BookMarkRequest.java
  src/main/java/umc/project/umark/domain/bookmark/repository/BookMarkRepository.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkService.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkServiceImpl.java
  src/main/java/umc/project/umark/domain/member/controller/MemberController.java
  src/main/java/umc/project/umark/domain/member/converter/MemberConverter.java
  src/main/java/umc/project/umark/domain/member/dto/MemberDto.java
  src/main/java/umc/project/umark/domain/member/service/MemberService.java
  src/main/java/umc/project/umark/domain/member/service/MemberServiceImpl.java
  src/main/java/umc/project/umark/global/config/SecurityConfig.java
  src/main/java/umc/project/umark/global/config/SwaggerConfig.java
  src/main/java/umc/project/umark/global/consts/UmarkStatic.java
Labels: feature

#63 [CI]: github actions 확인
  .github/workflows/dev_deploy.yml
  .gitignore
  src/main/resources/application.yml
Labels: ci/cd

#64 Ci/62
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/client_max_body_size.conf
  .platform/nginx.conf
  Procfile
  build.gradle
Labels: ci/cd

#65 [CHORE]/#62-오타 수정
  .github/workflows/dev_deploy.yml
Labels: ci/cd

#66 [FEAT]/#62-health API
  src/main/java/umc/project/umark/global/health/RootController.java
Labels: ci/cd

#67 [CHORE]/#62-region 변경
  .github/workflows/dev_deploy.yml
Labels: ci/cd

#68 [CHORE]/#62-공백 조절
  .github/workflows/dev_deploy.yml
Labels: ci/cd

#69 [CI]: CI/CD 파이프라인 구축
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .gitignore
  .platform/client_max_body_size.conf
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/umc/project/umark/global/health/RootController.java
  src/main/resources/application.yml
Labels: ci/cd

#74 [FIX]북마크 api 토큰 기반으로 수정
  src/main/java/umc/project/umark/domain/bookmark/controller/BookMarkController.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkService.java
  src/main/java/umc/project/umark/domain/bookmark/service/BookMarkServiceImpl.java
  src/main/java/umc/project/umark/domain/report/dto/Request/ReportRequest.java
  src/main/java/umc/project/umark/global/config/SecurityConfig.java
Labels: refactor
